### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by catbaron0** [DorasWorld2020/WonderfulLife.github.io#1]
1. 如果能提供 RSS 订阅就好了，如果你不在意网站的访问量的话。
1. 对于那些适合反复更新的页面，比如 `About me`，`图书推荐`，也许你可以考虑使用 `page` 而不是 `post`。

**Comment by DorasWorld2020** [comment]
> 1. 如果能提供 RSS 订阅就好了，如果你不在意网站的访问量的话。
> 2. 对于那些适合反复更新的页面，比如 `About me`，`图书推荐`，也许你可以考虑使用 `page` 而不是 `post`。

1. RSS订阅我看看怎么弄~
2. "About me" 我之前用的page，"图书推荐"用的post，我这周有空把其他一些反复更新的页面换成post
